import { execSync } from 'child_process';
import { writeFileSync, readFileSync } from 'fs';

const { version } = JSON.parse(readFileSync('package.json', 'utf-8'));
const commit = execSync('git rev-parse --short HEAD').toString().trim();
const time = new Date().toISOString();

writeFileSync(
  'src/version.ts',
  `// generated by npm run build:version\nexport const APP_VERSION = '${version}';\nexport const BUILD_COMMIT = '${commit}';\nexport const BUILD_TIME = '${time}';\n`,
);
